refactored to support zfs boot environment
added missing ROOTPW + added packer config for building vagrant boxes

change packer wait time + small improvements

added bash to Vagrantfile and completely disable sendmail in vm

diff --git a/tools/zfsinstall b/tools/zfsinstall
--- a/tools/zfsinstall
+++ b/tools/zfsinstall
@@ -3,12 +3,12 @@
 #
 # mfsBSD ZFS install script
 # Copyright (c) 2018 Martin Matuska <mm at FreeBSD.org>
+# Copyright (c) 2018 Fill Q <fill at NJoyX.net>
 #
 FREEBSD_MIRROR="${FREEBSD_MIRROR:-ftp://ftp.freebsd.org/pub/FreeBSD}"
-FS_LIST="var tmp"
 
 usage() {
-	echo "Usage: $0 [-h] -d geom_provider [-d geom_provider ...] [ -u dist_url ] [-r mirror|raidz] [-m mount_point] [-p zfs_pool_name] [-s swap_partition_size] [-z zfs_partition_size] [-c] [-C] [-l] [-4] [-A]"
+	echo "Usage: $0 [-h] -d geom_provider [-d geom_provider ...] [ -u dist_url ] [-r mirror|raidz] [-m mount_point] [-p zfs_pool_name] [-s swap_partition_size] [-z zfs_partition_size] [-c] [-C] [-l] [-4] [-A] [-L]"
 }
 
 osarch() {
@@ -17,6 +17,11 @@ osarch() {
 
 osrelease() {
 	/sbin/sysctl -n kern.osrelease | /usr/bin/sed -E -e 's,-p[0-9]+$,,g'
+}
+
+logerr() {
+	echo " error $1"
+	exit 1
 }
 
 help() {
@@ -37,6 +42,7 @@ help() {
 	echo "-l                : use legacy mounts (via fstab) instead of ZFS mounts"
 	echo "-4                : use fletcher4 as default checksum algorithm"
 	echo "-A                : align partitions to 4K blocks"
+	echo "-L                : enable compression (lz4 by default)"
 	echo; echo "Examples:"
 	echo "Install on a single drive with 2GB swap:"
 	echo "$0 -u /path/to/release -d da0 -s 2G"
@@ -48,9 +54,9 @@ help() {
 	echo "You can enable all swap partitions and/or make a gmirror-ed swap later."
 }
 
-while getopts d:u:t:r:p:s:z:m:V:Chcl4A o; do
+while getopts d:u:t:r:p:s:z:m:V:Chcl4AL o; do
 	case "$o" in
-        	d) DEVS="$DEVS ${OPTARG##/dev/}" ;;
+		d) DEVS="$DEVS ${OPTARG##/dev/}" ;;
 		u) URL="${OPTARG}" ;;
 		t) ARCHIVE="${OPTARG}" ;;
 		p) POOL="${OPTARG}" ;;
@@ -64,6 +70,7 @@ while getopts d:u:t:r:p:s:z:m:V:Chcl4A o; do
 		l) LEGACY=1 ;;
 		4) FLETCHER=1 ;;
 		A) ALIGN=1 ;;
+		L) COMPRESS=1 ;;
 		h) help; exit 1;;
 		[?]) usage; exit 1;;
 esac
@@ -203,9 +210,11 @@ fi
 if [ "${LEGACY}" = "1" ]; then
 	ALTROOT=
 	ROOTMNT=legacy
+	ZFS_FS_SCHEMA="/usr/share/mfsbsd/schema/legacy.zfs"
 else
 	ALTROOT="-o altroot=${MNT} -o cachefile=/boot/zfs/zpool.cache"
 	ROOTMNT=/
+	ZFS_FS_SCHEMA="/usr/share/mfsbsd/schema/default.zfs"
 fi
 
 # Fetch base.txz and kernel.txz
@@ -296,8 +305,7 @@ echo " done"
 if [ "${FLETCHER}" = "1" ]; then
 	echo -n "Setting default checksum to fletcher4 for ${POOL} ..."
 	if ! /sbin/zfs set checksum=fletcher4 ${POOL} > /dev/null 2> /dev/null; then
-		echo " error"
-		exit 1
+		logerr ""
 	fi
 	echo " done"
 fi
@@ -305,63 +313,75 @@ fi
 if [ "${LZJB}" = "1" ]; then
 	echo -n "Setting default compression to lzjb for ${POOL} ..."
 	if ! /sbin/zfs set compression=lzjb ${POOL} > /dev/null 2> /dev/null; then
-		echo " error"
-		exit 1
+		logerr ""
+	fi
+	echo " done"
+fi
+
+if [ "${COMPRESS}" = "1" ]; then
+	echo -n "Enabling compression (lz4) for ${POOL} ..."
+	if ! /sbin/zfs set compress=on ${POOL} > /dev/null 2> /dev/null; then
+		logerr ""
 	fi
 	echo " done"
 fi
 
 echo -n "Creating ${POOL} root partition:"
-if ! /sbin/zfs create -o mountpoint=${ROOTMNT} ${POOL}/root > /dev/null 2> /dev/null; then
-	echo " error"
-	exit 1
+if ! /sbin/zfs create -o mountpoint=none ${POOL}/ROOT > /dev/null 2> /dev/null; then
+	logerr ""
+fi
+if ! /sbin/zfs create -o mountpoint=${ROOTMNT} -o canmount=noauto ${POOL}/ROOT/default > /dev/null 2> /dev/null; then
+	logerr ""
 fi
 echo " ... done"
-echo -n "Creating ${POOL} partitions:"
-for FS in ${FS_LIST}; do
-	if [ "${LEGACY}" = 1 ]; then
-		MNTPT="-o mountpoint=legacy"
-	else
-		MNTPT=
-	fi
-	if ! /sbin/zfs create ${MNTPT} ${POOL}/root/${FS} > /dev/null 2> /dev/null; then
-		echo " error"
-		exit 1
-	fi
-	echo -n " ${FS}"
-done
-echo " ... done"
-echo -n "Setting bootfs for ${POOL} to ${POOL}/root ..."
-if ! /sbin/zpool set bootfs=${POOL}/root ${POOL} > /dev/null 2> /dev/null; then
-	echo " error"
-	exit 1
+
+# Mount rootfs
+echo -n "Mounting ${POOL}/ROOT/default on ${MNT} ..."
+/bin/mkdir -p ${MNT}
+if ! /sbin/mount -t zfs ${POOL}/ROOT/default ${MNT} > /dev/null 2> /dev/null; then
+	logerr "mounting ${POOL}/ROOT/default"
 fi
 echo " done"
+
+echo -n "Creating ${POOL} partitions:"
+__ZFS_CREATE=`/usr/bin/mktemp -q` || logerr "mktemp"
+/usr/bin/sort -f $ZFS_FS_SCHEMA | /usr/bin/tr -s '\n' '\n' | /usr/bin/awk -v pool="${POOL}" \
+	'{out=$2; for(i=3;i<=NF;i++){out=out" "$i}; print "/sbin/zfs create " out " " pool"/"$1}' \
+	> ${__ZFS_CREATE}
+if ! eval "$(cat ${__ZFS_CREATE})" > /dev/null 2> /dev/null; then
+	logerr ""
+fi
+/bin/rm -f ${__ZFS_CREATE}
+echo " ... done"
+
+echo -n "Setting bootfs for ${POOL} to ${POOL}/ROOT/default ..."
+if ! /sbin/zpool set bootfs=${POOL}/ROOT/default ${POOL} > /dev/null 2> /dev/null; then
+	logerr ""
+fi
+echo " done"
+
 /sbin/zfs list -r ${POOL}
+echo "---------"
+/bin/df -ah
+echo "========="
 
 # Mount and populate zfs (if legacy)
 if [ "${LEGACY}" = "1" ]; then
 	echo -n "Mounting ${POOL} on ${MNT} ..."
-	/bin/mkdir -p ${MNT}
-	if ! /sbin/mount -t zfs ${POOL}/root ${MNT} > /dev/null 2> /dev/null; then
-		echo " error mounting pool/root"
-		exit 1
+	__ZFS_MOUNTS=`/usr/bin/mktemp -q /tmp/$(basename $0).mounts` || logerr "mktemp"
+	/usr/bin/sort -f $ZFS_FS_SCHEMA  | /usr/bin/tr -s '\n' '\n' | /usr/bin/awk -v pool="${POOL}" -v mnt="${MNT}" \
+		'{ print "/bin/mkdir -p " mnt "/" $1 "\n" "/sbin/mount -t zfs " pool "/" $1 " " mnt "/" $1 }' \
+		> ${__ZFS_MOUNTS}
+	if ! eval "$(cat ${__ZFS_MOUNTS})" > /dev/null 2> /dev/null; then
+		logerr ""
 	fi
-	for FS in ${FS_LIST}; do
-		/bin/mkdir -p ${MNT}/${FS}
-		if ! /sbin/mount -t zfs ${POOL}/root/${FS} ${MNT}/${FS} > /dev/null 2> /dev/null; then
-			echo " error mounting ${POOL}/root/${FS}"
-			exit 1
-		fi
-	done
-echo " done"
+	echo " done"
 fi
 
 echo -n "Extracting FreeBSD distribution ..."
 for file in ${EXTRACT_FILES}; do
 	if ! /usr/bin/tar -C ${MNT} -x -f ${file} > /dev/null 2> /dev/null; then
-		echo " error"
-		exit 1
+		logerr ""
 	fi
 done
 echo " done"
@@ -370,61 +390,76 @@ echo " done"
 
 echo -n "Writing /boot/loader.conf..."
 echo "zfs_load=\"YES\"" > ${MNT}/boot/loader.conf
-echo "vfs.root.mountfrom=\"zfs:${POOL}/root\"" >> ${MNT}/boot/loader.conf
+if [ -n "${LEGACY}" ]; then
+	echo "vfs.root.mountfrom=\"zfs:${POOL}/root\"" >> ${MNT}/boot/loader.conf
+fi
 echo " done"
 
 # Write fstab if swap or legacy
 echo -n "Writing /etc/fstab..."
-rm -f ${MNT}/etc/fstab
-touch ${MNT}/etc/fstab
+/bin/rm -f ${MNT}/etc/fstab
+/usr/bin/touch ${MNT}/etc/fstab
 if [ -n "${FSWAP}" -o "${LEGACY}" = "1" ]; then
 	if [ -n "${FSWAP}" ]; then
 		echo "/dev/${FSWAP} none swap sw 0 0" > ${MNT}/etc/fstab
 	fi
 	if [ "${LEGACY}" = "1" ]; then
-		for FS in ${FS_LIST}; do
-			echo ${POOL}/root/${FS} /${FS} zfs rw 0 0 >> ${MNT}/etc/fstab
-		done
+		__ZFS_FSTAB=`/usr/bin/mktemp -q /tmp/$(basename $0).fstab` || logerr "mktemp"
+		/usr/bin/sort -f $ZFS_FS_SCHEMA  | /usr/bin/grep 'mountpoint=' | /usr/bin/awk -v pool="${POOL}" -v mnt="${MNT}" \
+			'{ print "echo " pool "/" $1 " /" $1 " zfs rw 0 0 >> " mnt "/etc/fstab" }' \
+			> ${__ZFS_FSTAB}
+		if ! eval "$(cat ${__ZFS_FSTAB})" > /dev/null 2> /dev/null; then
+			logerr ""
+		fi
+		/bin/rm -f ${__ZFS_FSTAB}
 	fi
 fi
+echo " done"
 if [ "${LEGACY}" != "1" ]; then
 	echo -n "Writing /etc/rc.conf..."
 	echo 'zfs_enable="YES"' >> ${MNT}/etc/rc.conf
 fi
+echo 'zfsd_enable="YES"' >> ${MNT}/etc/rc.conf
 echo " done"
 
 echo -n "Copying /boot/zfs/zpool.cache ..."
 if [ -n "${LEGACY}" ]; then
-	for FS in ${FS_LIST}; do
-		/sbin/umount ${MNT}/${FS} > /dev/null 2> /dev/null
-	done
+	__ZFS_UNMOUNTS=`/usr/bin/mktemp -q /tmp/$(basename $0).unmounts` || exit 1
+	/usr/bin/sort -r -f $ZFS_FS_SCHEMA | /usr/bin/tr -s '\n' '\n' | /usr/bin/awk -v mnt="${MNT}" \
+		'{ print "/sbin/umount " mnt "/" $1 }' \
+		> ${__ZFS_UNMOUNTS}
+	if ! eval "$(cat ${__ZFS_UNMOUNTS})" > /dev/null 2> /dev/null; then
+		logerr ""
+	fi
+	/bin/rm -f ${__ZFS_UNMOUNTS}
 	/sbin/umount ${MNT} > /dev/null 2> /dev/null
 fi
 if ! /sbin/zpool export ${POOL} > /dev/null 2> /dev/null; then
-	echo " error exporting pool"
-	exit 1
+	logerr " exporting pool"
 fi
 if ! /sbin/zpool import ${ALTROOT} ${POOL} > /dev/null 2> /dev/null; then
-	echo " error importing pool"
-	exit 1
+	logerr " importing pool"
+fi
+if ! /sbin/mount -t zfs ${POOL}/ROOT/default ${MNT} > /dev/null 2> /dev/null; then
+	logerr "mounting ${POOL}/ROOT/default"
 fi
 if [ -n "${LEGACY}" ]; then
-	if ! /sbin/mount -t zfs ${POOL}/root ${MNT} > /dev/null 2> /dev/null; then
-		echo " error mounting ${POOL}/root"
-		exit 1
+	echo -n "Mounting fs on ${MNT} ..."
+	if ! eval "$(cat ${__ZFS_MOUNTS})" > /dev/null 2> /dev/null; then
+		logerr "final mounting"
+	fi
+	/bin/rm -f ${__ZFS_MOUNTS}
+else
+	echo -n "Remounting fs on ${MNT} in correct order ..."
+	if ! /sbin/zfs umount -a > /dev/null 2> /dev/null; then
+		logerr "final umounting"
+	fi
+	if ! /sbin/zfs mount -a > /dev/null 2> /dev/null; then
+		logerr "final mounting"
 	fi
 fi
 if ! /bin/cp /boot/zfs/zpool.cache ${MNT}/boot/zfs/ > /dev/null 2> /dev/null; then
-	echo " error copying zpool.cache"
-	exit 1
-fi
-if [ -n "${LEGACY}" ]; then
-	for FS in ${FS_LIST}; do
-		if ! /sbin/mount -t zfs ${POOL}/${FS} ${MNT}/${FS} > /dev/null 2> /dev/null; then
-		echo " error mounting ${POOL}/${FS}"
-		exit 1
-		fi
-	done
+	logerr "copying zpool.cache"
 fi
 echo " done"
 
@@ -432,7 +467,7 @@ echo ""
 echo "Installation complete."
 echo "The system will boot from ZFS with clean install on next reboot"
 echo ""
-echo "You may make adjustments to the installed system using chroot:" 
+echo "You may make adjustments to the installed system using chroot:"
 echo "chroot ${MNT}"
 echo ""
 echo "Some adjustments may require a mounted devfs:"
